add get flow endpoints
gr4vy/gr4vy-openapi pull request #104
Opened 2022-02-21 22:07 UTC by epigos

# Description

Please include a summary of the change and which issue is fixed.

If you are a Gr4vy employee, please also reference the related Zoho tickets.
If you do not have a related Zoho ticket and this is more than a bug fix, then
create one now.

Fixes # (issue)
Re ... (Zoho ticket)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-02-23 07:19 UTC, bloowitt commented on reference/resources/flow_rule_outcome.yaml
> +  Conditions outcome. Support multiple outcome types (list/boolean etc.).
This looks a bit more like an internal note than something we should have on the external docs. Maybe better to phrase it like...
"Outcome that happens when the Rule matches. Currently the outcomes can be a boolean value, or a list of string values. What this outcome represents depends on the Action of which the Rule is a part of."

2022-02-23 07:23 UTC, bloowitt commented on reference/resources/flow_rule.yaml
> +    description: A list of outcomes.
In the Outcomes ref we define it as either a boolean or a list, so this should read:
"The outcome of this rule matching" or something similar.

2022-02-23 10:02 UTC, cbetta commented on reference/openapi.yaml
> +
```suggestion
  - name: Flow Rules
    description: |-
      In Gr4vy, flow rules represent the rules that trigger actions anywhere during the
      payment flow.
    x-internal: true

```

2022-02-23 10:03 UTC, cbetta commented on reference/openapi.yaml
> +      $ref: "./paths/flow__list-rules.yaml"
```suggestion
      $ref: "./paths/flows__list-rules.yaml"
```

2022-02-23 10:03 UTC, cbetta commented on reference/openapi.yaml
> +      - $ref: "./path-parameters/flow.yaml"
```suggestion
      - $ref: "./path-parameters/flow_id.yaml"
```

2022-02-23 10:04 UTC, cbetta commented on reference/openapi.yaml
> +  "/flows/{flow}/actions/{action}/rules/{rule_id}":
```suggestion
  "/flows/{flow_id}/actions/{action_id}/rules/{rule_id}":
```

Same question here, should it be `flow` and `action` or `flow_id` and `action_id`. The latter would be more consistent.

2022-02-23 10:18 UTC, epigos commented on reference/openapi.yaml
> +      $ref: "./paths/flow__list-rules.yaml"
Cool, will rename the file.

2022-02-23 10:28 UTC, cbetta requested changes
There's some mistakes in here that need fixing. I also provided some guidance on OpenAPI best practices for structuring complex data.

2022-02-23 10:28 UTC, cbetta commented on reference/openapi.yaml
> +      $ref: "./paths/flow__list-rules.yaml"
Generally the prefix matches the path, so `flows` and not `flow`.

2022-02-23 10:28 UTC, cbetta commented on reference/resources/flow_rule.yaml
> +    format: uuid
Every Gr4vy resource has an ID and a type.

The correct type for this would either be `rule` or `flow.action.rule`. I think the former will do.

2022-02-23 10:28 UTC, cbetta commented on reference/resources/flow_rule_condition.yaml
> +      - risk_score
We're not building this just yet. Remove?

2022-02-23 10:28 UTC, cbetta commented on reference/resources/flow_rule_outcome.yaml
> +        active: false
What is this for? We don't currently plan to allow rules to be activated/deactivated, but payment services can. The active state does not need to be stored on the rule.

2022-02-23 10:28 UTC, cbetta commented on reference/resources/flow_rules.yaml
> +title: Rules
```suggestion
title: Flow rules
```

2022-02-23 10:28 UTC, cbetta commented on reference/resources/flow_rules.yaml
> +description: A list of rules.
```suggestion
description: A list of rule in a flow.
```

2022-02-23 10:28 UTC, cbetta commented on reference/request-bodies/flow_rule_create_request.yaml
> +title: Rule Create
```suggestion
title: Create flow rule
```

2022-02-23 10:28 UTC, cbetta commented on reference/request-bodies/flow_rule_create_request.yaml
> +
This should have a min/max length?

2022-02-23 10:28 UTC, cbetta commented on reference/request-bodies/flow_rule_create_request.yaml
> +      $ref: "../openapi.yaml#/components/schemas/FlowRuleOutcome"
I am not sure this is an array. I think it's 1 object.

2022-02-23 10:28 UTC, cbetta commented on reference/request-bodies/flow_rule_update_request.yaml
> +    nullable: true
Why is this nullable?

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__update-rule.yaml
> +summary: Update Rule
```suggestion
summary: Update flow rule
```

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__update-rule.yaml
> +  Updates a given rule with new values.
```suggestion
  Updates a given flow rule.
```

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__delete-rule.yaml
> +summary: Delete Rule
```suggestion
summary: Delete flow rule
```

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__add-rule.yaml
> +summary: Create Rule
```suggestion
summary: Create flow rule
```

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__add-rule.yaml
> +                result: ["stripe", "gocardless"]
I am not sure it makes sense for `outcome` to be an array, unless I am missing something.

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__add-rule.yaml
> +  This rule will be inserted at the top/bottom position.
```suggestion
  This rule will be inserted at the top/bottom position.
```

Which one is it?

2022-02-23 10:28 UTC, cbetta commented on reference/paths/flow__list-rules.yaml
> +summary: List Rules
```suggestion
summary: List flow rules
```

2022-02-23 10:28 UTC, epigos commented on reference/openapi.yaml
> +      $ref: "./paths/flow__list-rules.yaml"
@cbetta Looking at the tag name is `Flow`, does this still needs to be renamed to `flows__*`?. This will also need to apply to all the flow files as I used the singular name.

2022-02-23 10:57 UTC, cbetta commented on reference/openapi.yaml
> +      $ref: "./paths/flow__list-rules.yaml"
Ah yeah. Hmmm. Leave it as flow.

2022-02-23 13:39 UTC, epigos commented on reference/paths/flow__add-rule.yaml
> +                result: ["stripe", "gocardless"]
Good catch. The outcome is an object and not array.

2022-02-23 13:44 UTC, epigos commented on reference/resources/flow_rule_condition.yaml
> +      - risk_score
Sure, will remove it.

2022-02-23 13:48 UTC, epigos commented on reference/resources/flow_rule_outcome.yaml
> +        active: false
So the rule is not storing the payment service details. It will retrieve it from the payment service model when creating the response for the request.

2022-02-23 15:11 UTC, epigos commented on reference/request-bodies/flow_rule_create_request.yaml
> +
Sounds good. I'm not sure we discussed the min/max conditions for each rule. @bloowitt @cbetta do you know the limits for conditions?

2022-02-23 18:10 UTC, cbetta commented on reference/resources/flow_rule_outcome.yaml
> +        active: false
I am not sure what you are saying @epigos

2022-02-23 18:10 UTC, cbetta commented on reference/request-bodies/flow_rule_create_request.yaml
> +
Please ask Sach.

2022-02-23 18:12 UTC, cbetta commented
@epigos make sure to run `yarn lint` locally to fix any formatting issues.

2022-02-25 15:07 UTC, epigos commented on reference/request-bodies/flow_rule_create_request.yaml
> +
@cbetta according to Sach, there are no limits to the conditions are the moment.

2022-03-17 09:25 UTC, cbetta commented on reference/paths/flow__update-rule.yaml
> +
Missing `x-internal`?

2022-03-17 09:28 UTC, cbetta approved these changes

2022-03-22 15:37 UTC, gryevns commented on reference/resources/flow_rule_outcome.yaml
> +      type: string
Is this the correct type, should it be the payment method enums?
https://github.com/gr4vy/gr4vy-openapi/blob/957762cf9eb3d8a2a1d274cdd81abd8a672d709f/reference/resources/payment_method.yaml#L41-L44

2022-03-22 15:37 UTC, gryevns commented on reference/request-bodies/flow_rule_create_request.yaml
> +    nullable: true
Are we sure this is nullable? I think this accepts an empty array but not sure about `null`.

2022-03-22 15:37 UTC, gryevns commented on reference/request-bodies/flow_rule_create_request.yaml
> +    nullable: true
Are we sure this is nullable? I think this must provide a string.

2022-03-22 15:37 UTC, gryevns commented on reference/resources/flow_payment_option_outcome.yaml
> +      Method tag for direct debit payment options e.g `Bank`.
```suggestion
      Optional group label for a given payment option, e.g. `Bank`
```

2022-03-22 15:37 UTC, gryevns commented on reference/resources/flow_amount_range_condition.yaml
> +        nullable: true
This is no longer nullable (same for `max`) because we merged https://github.com/gr4vy/core-api/pull/698

2022-03-22 15:37 UTC, gryevns commented on reference/resources/flow_amount_condition.yaml
> +        nullable: true
```suggestion
        nullable: false
```

2022-03-22 15:37 UTC, gryevns commented on reference/resources/flow_amount_condition.yaml
> +        maximum: 99999
Where did this value come from?

2022-03-22 16:25 UTC, epigos commented on reference/resources/flow_rule_outcome.yaml
> +      type: string
Yeah,  that is correct.

2022-03-22 16:25 UTC, epigos commented on reference/request-bodies/flow_rule_create_request.yaml
> +    nullable: true
ok, will remove the nullable flag

2022-03-22 16:28 UTC, epigos commented on reference/resources/flow_amount_condition.yaml
> +        maximum: 99999
Might have copied from one of the amount schemas in the specs. I think it should be `99999999` instead as per the transaction capture request schema.

2022-03-23 11:11 UTC, cbetta approved these changes

2022-03-23 11:11 UTC, cbetta commented on reference/paths/flow__add-rule.yaml
> +          $ref: "../openapi.yaml#/components/schemas/Error409DuplicateRecord"
Do we ever actually raise a 409?

2022-03-23 11:11 UTC, cbetta commented on reference/paths/flow__update-rule.yaml
> +  - Flow
This needs an `x-internal: true` like all other endpoints

2022-03-23 11:11 UTC, cbetta commented on reference/request-bodies/flow_rule_create_request.yaml
> +    $ref: "../openapi.yaml#/components/schemas/FlowRuleOutcome"
```suggestion
  outcome:
allOf:
  - $ref: "../openapi.yaml#/components/schemas/FlowRuleOutcome"
  - nullable: true
     description: The outcome of this rule matching.
```

2022-03-23 11:11 UTC, cbetta commented on reference/request-bodies/flow_rule_update_request.yaml
> +    example: 2
```suggestion
allOf:
  - $ref: "../openapi.yaml#/components/schemas/FlowRuleCreateRequest"
  - properties:
       position:
          description: The position of the rule in the flow.
          type: number
          example: 2
```

2022-03-23 11:11 UTC, cbetta reviewed
[Deleted]

2022-03-23 11:12 UTC, cbetta requested changes
Requested changes

2022-03-24 11:33 UTC, epigos commented on reference/paths/flow__add-rule.yaml
> +          $ref: "../openapi.yaml#/components/schemas/Error409DuplicateRecord"
We don't raise it. Will remove it.

2022-03-29 10:00 UTC, cbetta approved these changes

2022-03-29 10:08 UTC, merged