feat: add ip_address [TA-809]
gr4vy/gr4vy-openapi pull request #110
Opened 2022-03-03 15:14 UTC by szeying-lee

# Description

Please include a summary of the change and which issue is fixed.

If you are a Gr4vy employee, please also reference the related Zoho tickets.
If you do not have a related Zoho ticket and this is more than a bug fix, then
create one now.

Fixes # (issue)
Re ... (Zoho ticket)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-03-11 09:53 UTC, thomas-gr4vy reviewed
Looks good. Just one question RE the transaction create endpoint.

2022-03-11 09:53 UTC, thomas-gr4vy commented on reference/request-bodies/card_request.yaml
> +  ip_address:
`ip_address` is also on the transaction create schema. What will happen if I provide an IP address in both?

2022-03-11 10:39 UTC, szeying-lee commented on reference/request-bodies/card_request.yaml
> +  ip_address:
The POST /transactions logic for this change in Core API only uses the outer `ip_address`, meaning any `ip_address` passed as part of the payment method is ignored but won't raise any errors. Do you think I should be checking for both in case `ip_address` is supplied in the payment method but not in the outer transaction? 🤔

2022-03-17 09:34 UTC, cbetta requested changes

2022-03-17 09:34 UTC, cbetta commented on reference/paths/payment_methods__approve-payment-method.yaml
> +
I guess we need to do this cause we don't intend to store the IP?

2022-03-17 09:34 UTC, cbetta commented on reference/paths/payment_methods__store-payment-method.yaml
> +                    example: "111.111.111.111"
Why not just add this to `CardRequest` and `RedirectRequest`?

2022-03-17 09:34 UTC, cbetta commented on reference/paths/payment_methods__store-payment-method.yaml
> +                    example: "111.111.111.111"
Definitely not the right way to do this (sorry). 

1. Properties should not be listed here, the new properties should be part of a named schema (e.g. CardRequest)
2. We should make the value nullable
3. We should maybe just design the API to expect the IP always within the same place, regardless of API call.

Happy to jump on a call to do this the right way together.

2022-03-17 09:41 UTC, szeying-lee commented on reference/paths/payment_methods__approve-payment-method.yaml
> +
This particular endpoint is a GET endpoint even though it sends a request to the connector. Although FastAPI supports sending a request body with a GET, it isn't recommended: https://fastapi.tiangolo.com/tutorial/body/

2022-03-17 09:46 UTC, szeying-lee commented on reference/paths/payment_methods__store-payment-method.yaml
> +                    example: "111.111.111.111"
My initial changes did add them to `CardRequest` and `RedirectRequest`, however doing so would allow `ip_address` to be sent as part of these payment methods in create transaction requests as well. See also the point Thomas raised: https://github.com/gr4vy/gr4vy-openapi/pull/110#discussion_r824554601

Have discussed with him and decided it would be best that the schemas should ask only for what is needed, so removed it out of those resources and extended it this way. However, I see your point and I should have made a new schema, maybe something like `CardRequestWithIpAddress` or similar, that extends `CardRequest` and adds `ip_address` as an extra property, and then reference it here.

2022-03-17 10:59 UTC, cbetta commented
Closing this in favour of a different approach after conversation with @szeying-lee

2022-03-17 10:59 UTC, closed without merging