task: update spec with support to toggle tokenization
gr4vy/gr4vy-openapi pull request #124
Opened 2022-03-28 09:02 UTC by luca-gr4vy

# Description

Adds specification for the PS tokenization toggle support.

Depends on: https://github.com/gr4vy/core-api/pull/725

Fixes: https://gr4vy.atlassian.net/browse/TA-1112

Screenshot(s):

<img width="667" alt="Screenshot 2022-03-28 at 11 01 37" src="https://user-images.githubusercontent.com/101414321/160364030-0fb5c938-c9ee-4bed-859b-13d2e94b797a.png">

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-03-28 09:04 UTC, luca-gr4vy commented
@cbetta getting some warnings when running the linter locally, seemingly unrelated to these changes. Is that ok?

<img width="613" alt="Screenshot 2022-03-28 at 10 56 10" src="https://user-images.githubusercontent.com/101414321/160364305-d00faaac-3a1a-457b-9511-c7122eb48107.png">

2022-03-31 09:02 UTC, cbetta commented
> @cbetta getting some warnings when running the linter locally, seemingly unrelated to these changes. Is that ok?
> 
> <img alt="Screenshot 2022-03-28 at 10 56 10" width="613" src="https://user-images.githubusercontent.com/101414321/160364305-d00faaac-3a1a-457b-9511-c7122eb48107.png">

Yes those are expected

2022-04-12 10:27 UTC, thomas-gr4vy requested changes

2022-04-12 10:27 UTC, thomas-gr4vy commented on reference/resources/payment_option.yaml
> +  payment_method_tokenization_enabled:
This hasn't been added to `/payment-options`. Instead, the value of the existing `can_store_payment_method` property takes `payment_method_tokenization_enabled` into account.

2022-04-12 11:17 UTC, luca-gr4vy commented on reference/resources/payment_option.yaml
> +  payment_method_tokenization_enabled:
thanks, removed

2022-04-13 14:42 UTC, cbetta approved these changes

2022-04-14 09:12 UTC, thomas-gr4vy approved these changes

2022-04-14 09:17 UTC, merged