feat(flow): add card transaction schema
gr4vy/gr4vy-openapi pull request #127
Opened 2022-03-31 17:20 UTC by epigos

# Description

Adds a new schema for flow card transactions rule API.

Fixes # (issue)

https://gr4vy.atlassian.net/browse/TA-1074

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-04-01 13:58 UTC, bloowitt commented on reference/resources/flow_card_bin_condition.yaml
> +title: Flow card bin condition
BIN should be uppercase (it's an acronym for Bank Identification Number).

2022-04-01 14:02 UTC, bloowitt commented on reference/resources/flow_card_scheme_condition.yaml
> +    example:
if the example is for "value" (not sure with the indentation in Github), should it not be a list? so `["visa", "mastercard"]`

2022-04-01 14:03 UTC, bloowitt commented on reference/resources/flow_card_source_condition.yaml
> +      - "raw"
Same as above

2022-04-01 14:03 UTC, bloowitt commented on reference/enums/flow_action.yaml
> +  Action to for the given rule.
@cbetta should we have a note here indicating that specific actions belong to specific flows?

2022-04-01 14:04 UTC, bloowitt requested changes
Left a couple comments

2022-04-06 12:53 UTC, epigos commented on reference/enums/flow_action.yaml
> +  Action to for the given rule.
@bloowitt I've updated the description with flow-action mapping.

2022-04-07 08:39 UTC, bloowitt approved these changes

2022-05-05 09:25 UTC, cbetta commented on reference/enums/flow_action.yaml
> +example: select-payment-options
```suggestion
  Action for the given rule. Actions can only be used in flows that support them.
  
  * The `checkout` flow only supports the `select-payment-options` action.
  * The `card-transaction` currently only supports the `route-transaction` action.
example: select-payment-options
```

2022-05-05 09:27 UTC, cbetta commented on reference/path-parameters/flow.yaml
> +    - $ref: "../enums/flow.yaml"
Not sure this will work well with SDKs. I think this can just be.

```
schema:
  $ref: "../enums/flow.yaml"
```

2022-05-05 09:28 UTC, cbetta commented on reference/path-parameters/flow_action.yaml
> +    - $ref: "../enums/flow_action.yaml"
```suggestion
  $ref: "../enums/flow_action.yaml"
```

2022-05-05 12:51 UTC, gryevns commented on reference/resources/flow_tokenised_payment_method_condition.yaml
> +---
I think we can remove this file?

2022-05-09 09:23 UTC, gryevns submitted a review, later dismissed

2022-05-09 10:16 UTC, cbetta commented on reference/resources/flow_rule.yaml
> +      - $ref: "../enums/flow.yaml"
```suggestion
    allOf:
      - $ref: "../enums/flow.yaml"
      - example: checkout
```

2022-05-09 10:16 UTC, cbetta commented on reference/resources/flow_rule.yaml
> +      - $ref: "../enums/flow_action.yaml"
```suggestion
    allOf:
      - $ref: "../enums/flow_action.yaml"
      - example: select-payment-options
```

2022-05-09 10:19 UTC, cbetta requested changes

2022-05-09 10:19 UTC, cbetta commented on reference/resources/flow_rule_payment_method_list_outcome.yaml
> +  - $ref: "../enums/methods.yaml"
I don't think this should be a resource. Instead, where you are using this resource just do an `allOf` with the `ref` and custom description.

2022-05-11 08:53 UTC, cbetta commented on reference/resources/flow_rule.yaml
> +      - $ref: "../enums/flow.yaml"
@epigos not sure this got resolved.

2022-05-11 09:43 UTC, cbetta approved these changes

2022-05-11 09:57 UTC, gryevns approved these changes

2022-05-11 10:01 UTC, merged