feat: added payment_method_id to card-details endpoint [TA-1301]
gr4vy/gr4vy-openapi pull request #137
Opened 2022-04-21 10:18 UTC by thomas-gr4vy

# Description

Adds the `payment_method_id` to the query string of the `[GET] /card-details` endpoint, allowing users to query card details using **either** the card's BIN or the ID of a stored payment method.

Updates the response to return the `id` as either the BIN or payment method ID, dependant upon which was provided in the original request.

Re [TA-1301](https://gr4vy.atlassian.net/browse/TA-1301)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-04-22 09:29 UTC, cbetta commented on reference/paths/card-details.yaml
> +  cards `payment_method_id` or any other payment card using that cards BIN.
```suggestion
  Retrieves details about a card using either that
  card's BIN or for stored cards the `payment_method_id`.
```

2022-04-22 09:31 UTC, cbetta requested changes

2022-04-22 09:31 UTC, cbetta commented on reference/resources/card_details.yaml
> +      - $ref: "./../resources/payment_method.yaml#/properties/id"
Do you think we should just return the BIN even for a stored card? In other words keep this as it was?

2022-04-25 10:17 UTC, thomas-gr4vy commented on reference/resources/card_details.yaml
> +      - $ref: "./../resources/payment_method.yaml#/properties/id"
As discussed in Slack, the `id` will be either the 8-digit BIN (when looking up card details using the BIN), or `null` (when looking up card details using the `payment_method_id`).

2022-04-29 10:19 UTC, danielknell approved these changes

2022-04-29 10:26 UTC, merged