feat: add approval target
gr4vy/gr4vy-openapi pull request #152
Opened 2022-05-13 08:41 UTC by douglaseggleton

# Description

Approval urls will occasionally have a hard requirement to continue the transaction in a blank window. This will only be returned for the payment methods that need it. The terminology of 'target' makes more sense to echo that of `self|blank` in a browser link. This also means we don't have to have context of Embed to interpret what a 'approval mode' means.

<img width="1002" alt="Screenshot 2022-05-13 at 09 34 34" src="https://user-images.githubusercontent.com/1008377/168244850-c7231509-69e4-4307-b547-fa7f44ac89da.png">

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-05-16 09:11 UTC, thomas-gr4vy requested changes

2022-05-16 09:11 UTC, thomas-gr4vy commented on reference/resources/payment_service_definition.yaml
> +        description: Target than an approval URL must be opened in.
```
The optional target that an approval URL must be opened in.
If not provided, there is no specific requirement.
```

2022-05-16 09:11 UTC, thomas-gr4vy commented on reference/resources/payment_method.yaml
> +    description: The optional target than an approval URL must be opened in.
**Typo:** The optional target ~than~ that an approval URL must be opened in.

2022-05-16 09:11 UTC, thomas-gr4vy commented on reference/resources/payment_method--tokenized.yaml
> +    description: The optional target than an approval URL must be opened in.
**Typo:** The optional target ~than~ that an approval URL must be opened in.

2022-05-16 09:11 UTC, thomas-gr4vy commented on reference/resources/payment_method--snapshot.yaml
> +    description: The optional target than an approval URL must be opened in.
**Typo:** The optional target ~than~ that an approval URL must be opened in.

2022-05-16 09:17 UTC, cbetta commented on reference/resources/payment_method.yaml
> +      - blank
We seem to re-use this prop all over. Might be easier to make a ref.

For example

```suggestion
  approval_target:
    $ref: "../properties/approval_target.yaml"
```

2022-05-19 11:44 UTC, douglaseggleton commented on reference/resources/payment_method--snapshot.yaml
> +
Discussed in standup - We are going to implement as replacing `blank` with `new_window` but not include additional values for now.

2022-05-19 18:43 UTC, douglaseggleton commented on reference/resources/payment_method--snapshot.yaml
> +    example: blank
```suggestion
    example:  "new_window"
```

2022-05-19 18:43 UTC, douglaseggleton commented on reference/resources/payment_method--snapshot.yaml
> +      - blank
```suggestion
      - "new_window"
```

2022-05-19 18:44 UTC, douglaseggleton commented on reference/properties/approval_target.yaml
> +example: blank
```suggestion
example: "new_window"
```

2022-05-19 18:44 UTC, douglaseggleton commented on reference/properties/approval_target.yaml
> +  - blank
```suggestion
  - "new_window"
```

2022-05-24 13:35 UTC, thomas-gr4vy commented on reference/properties/approval_target.yaml
> +  - "new_window"
```suggestion
  - "new_window"
  - "any"
```

2022-05-30 13:24 UTC, thomas-gr4vy approved these changes

2022-05-30 13:24 UTC, thomas-gr4vy commented on reference/properties/approval_target.yaml
> +  If not provided, there is no specific requirement.
nitpick
```suggestion
  If `any` or `null`, then there is no specific requirement.
```

2022-05-30 13:27 UTC, merged