Required fields for wallets & TH tax ID kind
gr4vy/gr4vy-openapi pull request #185
Opened 2022-07-13 15:43 UTC by cbetta

Re TA-2146

2022-07-13 16:40 UTC, Dave-Elec requested changes

2022-07-13 16:40 UTC, Dave-Elec commented on reference/resources/required_fields.yaml
> -title: Card Required Fields
Is required fields descriptive?

2022-07-13 16:48 UTC, cbetta commented on reference/resources/required_fields.yaml
> -title: Card Required Fields
I think so. There is a description with more details.

2022-07-13 17:08 UTC, Dave-Elec commented on reference/resources/required_fields.yaml
> -title: Card Required Fields
I meant the file name.

2022-07-14 09:04 UTC, cbetta commented
@douglaseggleton what's your thoughts on fitting `required_fields` under context? I have trouble understanding what needs to go in context and what not.

2022-07-14 10:57 UTC, Dave-Elec commented on reference/resources/required_fields.yaml
> -title: Card Required Fields
Okay.

2022-07-18 10:19 UTC, douglaseggleton commented
> IMO `context` should be reserved for payment method specific data (ie. we can't rely on the presence of specific items as they can differ between payment methods). This is how it currently works with Google/Apple Pay; both add additional items to the `context` which are not necessarily present for other payment methods. If `required_fields` is applied across all methods then my suggestion would be to move it to the top level.

100% agree with @thomas-gr4vy 👍🏻

2022-07-25 13:38 UTC, thomas-gr4vy commented
> @thomas-gr4vy @douglaseggleton just spotted these comments while we just shipped the core API change that does put this under context. Would this be an easy change to move?

As @douglaseggleton highlighted, `approval_ui` is within `context` too, so I think it's fine to continue as-is and migrate both to the top-level as a future improvement?

2022-07-25 14:08 UTC, merged