feat: add spec for checkout sessions/secure fields [TA-1834]
gr4vy/gr4vy-openapi pull request #189
Opened 2022-07-28 13:33 UTC by thomas-gr4vy

# Description

This PR adds specifications for the following endpoints:
- `POST` /checkout/sessions
- `GET` /checkout/sessions/{id}
- `DELETE` /checkout/sessions/{id}
- `PUT` /checkout/sessions/{id}/fields

This PR updates the following specifications to add `checkout-session` as an acceptable payment method:
- `POST` /transactions
- `POST` /payment-methods

Re [TA-2252](https://gr4vy.atlassian.net/browse/TA-2252)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-07-28 16:47 UTC, cbetta commented on reference/openapi.yaml
> +      $ref: "./paths/checkout_session__add-session.yaml"
@thomas-gr4vy these paths are generally the plural. E.g. `/checkout-sessions`

2022-07-28 16:52 UTC, cbetta commented on reference/paths/checkout_session__add-session.yaml
> +    description: Returns details about a current Checkout Session.
```suggestion
    description: Returns the new Checkout Session.
```

2022-07-28 17:00 UTC, cbetta requested changes
@thomas-gr4vy few small improvements and questions.

2022-07-28 17:00 UTC, cbetta commented on reference/paths/checkout_session_fields__update-fields.yaml
> +description: Updates the Secure Fields of the Checkout Session.
```suggestion
description: |-
  Updates the Secure Fields of the Checkout Session. Once the fields have been
  received the `expiration_date` will be updated to 5 minutes from the time of 
  receipt.
```

2022-07-29 08:47 UTC, thomas-gr4vy commented on reference/paths/checkout_session_fields__update-fields.yaml
> +  "200":
We return a `200` for all other update endpoints. For example:
https://github.com/gr4vy/gr4vy-openapi/blob/8b9c8164e223a59682302733128407b5e28a3cd8/reference/paths/buyers__update-buyer.yaml#L20:L27

2022-07-29 08:52 UTC, thomas-gr4vy commented on reference/request-bodies/checkout_sessions_fields_update_request.yaml
> +        example: "123"
I have updated this to reference the existing `CardRequest`. This adds properties like `buyer_id` and `buyer_external_identifier`, however, as we are likely to re-use the same schema internally then these will be valid. Do we think this is OK?

2022-08-01 09:35 UTC, luca-gr4vy commented on reference/paths/checkout_sessions__delete-session.yaml
> +description: Delete a Checkout Session.
```suggestion
description: Deletes a Checkout Session.
```

I guess, if we're going for third person in the description, for consistency's sake

2022-08-05 09:11 UTC, cbetta approved these changes

2022-08-05 09:11 UTC, cbetta commented
@thomas-gr4vy all LGTM

2022-08-05 11:41 UTC, cbetta approved these changes

2022-08-05 15:09 UTC, merged