feat: payment-services endpoint should return only active or deleted [TA-2401]
gr4vy/gr4vy-openapi pull request #202
Opened 2022-08-25 09:51 UTC by Dave-Elec

# Description

This PR updates /payment-services endpoint to include `deleted` query parameter.
This allows either deleted or active payment services to be listed.

Jira: [TA-2401](https://gr4vy.atlassian.net/browse/TA-2401)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-08-25 12:54 UTC, cbetta commented on reference/paths/payment_services__list-payment-services.yaml
> +  - $ref: "../query-parameters/list_payment_services__deleted.yaml"
Can we rename this to `deleted.yml`?

2022-08-26 13:32 UTC, thomas-gr4vy requested changes

2022-08-26 13:32 UTC, thomas-gr4vy commented on reference/query-parameters/deleted.yaml
> +  example: false
```suggestion
  example: true
  default: false
```

2022-08-26 13:32 UTC, thomas-gr4vy commented on reference/query-parameters/deleted.yaml
> +  When set to `false`, filter for payment services that are active.
```suggestion
  Filters the results to only show items which have been deleted.
  By default, deleted items will not be returned.
```

2022-08-26 13:32 UTC, thomas-gr4vy commented on reference/query-parameters/deleted.yaml
> +  example: false
As a user is unlikely to ever use `deleted=false` (it's unnecessary) we should instead show the intended usage of filtering to only show deleted items by settings `deleted=true`.

2022-08-26 13:32 UTC, thomas-gr4vy commented on reference/query-parameters/deleted.yaml
> +  When set to `false`, filter for payment services that are active.
We made this parameter generic when we renamed it to `deleted` so we should make the description generic also.

2022-08-26 13:55 UTC, thomas-gr4vy approved these changes
Looks good to me, as long as @cbetta is happy too.

2022-08-26 15:38 UTC, cbetta approved these changes

2022-08-29 08:46 UTC, merged