feat: adding last_login_at to user schema
gr4vy/gr4vy-openapi pull request #247
Opened 2022-11-22 20:07 UTC by galbino

# Description
Adds the `last_login_at` to the user schema, changing, subsequently, all endpoints that uses User.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/29392550/203409574-268fab29-fad3-49e5-9afc-19d8de3eb0a2.png">
Re TA-3207

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own changes
- [X] I have run `yarn test` to make sure my changes pass all linters
- [X] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-11-28 17:07 UTC, cbetta requested changes
Please rename to `last_logged_in_at`.

2022-11-28 17:08 UTC, galbino commented
> Please rename to `last_logged_in_at`.

I used that name because it was the variable used on the model already. Should I change it to that one then?

2022-11-29 14:38 UTC, galbino commented
> Please rename to `last_logged_in_at`.

@cbetta I used that name because it was the variable used on the model already. Should I change it to that one then?
<img width="513" alt="image" src="https://user-images.githubusercontent.com/29392550/204558139-8732a455-ad0e-4c1c-b2af-1948a672d1f4.png">

2022-11-29 19:13 UTC, cbetta approved these changes

2022-11-30 18:42 UTC, merged