feat(apple-pay-certs): Add /apple-pay-certificates endpoints [TA-3300]
gr4vy/gr4vy-openapi pull request #253
Opened 2022-11-29 10:50 UTC by szeying-lee

# Description
Adds descriptions, resources and endpoints of the `/apple-pay-certificates` endpoints.

Fixes # (issue)
[TA-3300](https://gr4vy.atlassian.net/browse/TA-3300)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-11-29 14:16 UTC, cbetta commented on reference/openapi.yaml
> +      certificate if you wish to use Apple Pay with Gr4vy mobile SDKs.
```suggestion
      certificate if you wish to use Apple Pay with Gr4vy's mobile SDKs.
```

2022-11-29 14:19 UTC, cbetta commented on reference/paths/apple_pay_certificates__add-apple-pay-certificate.yaml
> +summary: New Apple Pay certificate registration
```suggestion
summary: Start registering an Apple Pay certificate
```

All endpoints start with a verb.

2022-11-29 14:21 UTC, cbetta commented on reference/paths/apple_pay_certificates__delete-apple-pay-certificate.yaml
> +summary: Delete an Apple Pay certificate
```suggestion
summary: Remove Apple Pay certificate
```

2022-11-29 14:22 UTC, cbetta commented on reference/resources/apple_pay_certificate.yaml
> +      - enabled
```suggestion
      - active
```

Let's change it as agreed

2022-11-29 14:25 UTC, cbetta requested changes
Left a few small comments for changes. Rest looks great.

2022-11-29 16:10 UTC, douglaseggleton commented on reference/paths/apple_pay_certificates__add-apple-pay-certificate.yaml
> +  "401":
Do we need to list any of the other error status codes?

2022-11-29 16:11 UTC, douglaseggleton commented on reference/paths/apple_pay_certificates__list-apple-pay-certificates.yaml
> +                  status: enabled
Did we change this to active?

2022-11-30 13:01 UTC, cbetta commented on reference/paths/apple_pay_certificates__add-apple-pay-certificate.yaml
> +  "401":
Generally we only document the 401s and 403s I think. Don't think 403 is relevant here.

2022-11-30 15:30 UTC, szeying-lee commented on reference/openapi.yaml
> +      certificate if you wish to use Apple Pay with Gr4vy mobile SDKs.
Done: https://github.com/gr4vy/gr4vy-openapi/pull/253/commits/1fb3b7c46bf34637287750c2fd8639535a47be0b

2022-11-30 15:30 UTC, szeying-lee commented on reference/resources/apple_pay_certificate.yaml
> +      - enabled
Changed: https://github.com/gr4vy/gr4vy-openapi/pull/253/commits/e697131dd7235e06b35a05e2b3674dd57a6b801c

2022-11-30 15:31 UTC, szeying-lee commented on reference/paths/apple_pay_certificates__list-apple-pay-certificates.yaml
> +                  status: enabled
https://github.com/gr4vy/gr4vy-openapi/pull/253/commits/e697131dd7235e06b35a05e2b3674dd57a6b801c

2022-11-30 15:32 UTC, szeying-lee commented on reference/openapi.yaml
> +      * List all Apple Pay certificates.
Are these endpoints be internal? I've kinda written the descriptions for a merchant audience 😅 .
Added the flag here anyway (and to the other new resources): https://github.com/gr4vy/gr4vy-openapi/pull/253/commits/15da8fb43dfc5b07bc5579b711935ac55651c676

2023-01-31 17:27 UTC, cbetta commented on reference/openapi.yaml
> +      * List all Apple Pay certificates.
I think we can keep them internal for now until a merchant needs them.

2023-01-31 17:28 UTC, cbetta approved these changes

2023-01-31 17:28 UTC, douglaseggleton approved these changes
Looks good to me - Only question from me is around the need for `x-internal: true`?

2023-02-01 09:35 UTC, merged