feat(roles): add roles to list-users endpoint
gr4vy/gr4vy-openapi pull request #262
Opened 2022-12-08 21:48 UTC by epigos

# Description

Please include a summary of the change and which issue is fixed.

If you are a Gr4vy employee, please also reference the related Zoho tickets.
If you do not have a related Zoho ticket and this is more than a bug fix, then
create one now.

[TA-3206](https://gr4vy.atlassian.net/browse/TA-3206)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-12-09 09:27 UTC, cbetta commented on reference/resources/user.yaml
> +    description: A list of roles.
```suggestion
    description: The roles this user has been assigned.
```

2022-12-09 13:00 UTC, cbetta commented on reference/query-parameters/roles.yaml
> +  assigned to them. It support multiple role IDs.
```suggestion
schema:
  type: array
  items:
    type: string
  example: 
    - 8724fd24-5489-4a5d-90fd-0604df7d3b83
in: query
name: roles
description: |-
  Filters the results to only match the users that have any `roles`
  that matches with any of the provided role IDs.
```

2022-12-09 13:01 UTC, cbetta requested changes

2022-12-09 13:01 UTC, cbetta commented on reference/query-parameters/roles.yaml
> +  assigned to them. It support multiple role IDs.
This follows the format we use here as well https://github.com/gr4vy/gr4vy-openapi/blob/main/reference/query-parameters/list_transactions__status.yaml

2022-12-09 13:57 UTC, cbetta commented on reference/query-parameters/roles.yaml
> +  example:
```suggestion
  example:
```

2022-12-13 13:42 UTC, thomas-gr4vy approved these changes

2022-12-13 14:00 UTC, cbetta approved these changes

2022-12-13 14:01 UTC, merged