Test all of change
gr4vy/gr4vy-openapi pull request #31
Opened 2021-04-23 06:03 UTC by steve-gr4vy

# Description

These changes are required to 'help' the go openapi generator create correct working sdk.  I have also tested the changes against the node sdk.

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own changes
- [x ] I have run `yarn test` to make sure my changes pass all linters
- [x ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2021-04-23 09:47 UTC, cbetta approved these changes

2021-04-23 09:47 UTC, cbetta commented on reference/resources/card_rule_number_condition.yaml
Why did we remove this?

2021-04-23 09:47 UTC, cbetta commented on reference/resources/payment_service_definition.yaml
> -            - number
Likewise, why did we remove these?

2021-04-23 09:48 UTC, cbetta requested changes
Bit unclear why we removed some enums.

2021-04-23 10:11 UTC, steve-gr4vy commented on reference/resources/card_rule_number_condition.yaml
The Go sdk generator was creating duplicate types that caused compile errors - e.g. 
`
api/gr4vy.gen.go:165:2: CardRuleNumberConditionOperator is not a type
api/gr4vy.gen.go:167:2: CardRuleNumberConditionOperator is not a type
api/gr4vy.gen.go:169:2: CardRuleNumberConditionOperator is not a type
api/gr4vy.gen.go:171:2: CardRuleNumberConditionOperator is not a type
api/gr4vy.gen.go:173:2: CardRuleNumberConditionOperator is not a type
api/gr4vy.gen.go:474:2: PaymentServiceDefinitionFieldsFormatMultiline redeclared in this block
	previous declaration at api/gr4vy.gen.go:465:87
api/gr4vy.gen.go:476:2: PaymentServiceDefinitionFieldsFormatNumber redeclared in this block
	previous declaration at api/gr4vy.gen.go:467:84
api/gr4vy.gen.go:478:2: PaymentServiceDefinitionFieldsFormatText redeclared in this block
	previous declaration at api/gr4vy.gen.go:469:82
api/gr4vy.gen.go:954:6: CardRuleNumberConditionOperator redeclared in this block
	previous declaration at api/gr4vy.gen.go:163:68
api/gr4vy.gen.go:1656:6: PaymentServiceDefinitionFieldsFormat redeclared in this block
	previous declaration at api/gr4vy.gen.go:1653:6
`

2021-04-27 10:54 UTC, cbetta requested changes
Sorry but not going to be able to approve this. We can't just go and strip some of the enums for an SDK. We either need to update the SDK Spec build (https://github.com/gr4vy/gr4vy-openapi/blob/main/scripts/build-sdk-spec.js) or clean up the spec after it's been downloaded for use by the Go generator.

2021-04-27 11:01 UTC, cbetta approved these changes

2021-04-27 11:01 UTC, merged