feat(multi-merchant): Associate Network Tokens configuration to merchant accounts [TA-4288]
gr4vy/gr4vy-openapi pull request #331
Opened 2023-05-08 15:41 UTC by victormferrara

# Description

This feature is not yet ready but there are a few things about the interface that I'd like discuss/clarify and I though it would be easier to do so over the spec. I'll add some comments inline.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2023-05-08 15:53 UTC, victormferrara commented on reference/paths/merchant-accounts__new-merchant-account.yaml
> +            visa_network_token_app_id: ca12b3d0-4e23-41a9-906f-e5cbb8e6a731
The task ([TA-4288](https://gr4vy.atlassian.net/browse/TA-4288)) specifies this naming, equivalent to the original environment variables, but I'd say that being a feature it looks better in plural as we do with the internal feature flag, e.g: `visa_network_tokens_requestor_id`. Thoughts?

2023-05-08 15:53 UTC, victormferrara commented on reference/request-bodies/merchant_account_create.yaml
> +  visa_network_token_requestor_id:
Internally we are storing this in a different table where we have `(merchant_account_id, scheme, requestor_id, app_id)`. In the API it's probably easier to have these flattened variables, but I want to mention this in case we prefer to provide/retrieve a similar collection.

2023-05-08 15:53 UTC, victormferrara commented on reference/request-bodies/merchant_account_create.yaml
> +      Requestor ID provided by VISA after onboarding to use Network Tokens.
Given that merchants can't make the onboarding themselves, do we want to document all this publicly?

2023-05-08 15:53 UTC, victormferrara commented on reference/request-bodies/merchant_account_update.yaml
> +  visa_network_token_requestor_id:
As we do with the webhook parameters, if not provided in the update they are going to be removed from the DB instead of ignored. Is that the expected behavior?

2023-05-10 14:53 UTC, cbetta commented on reference/paths/merchant-accounts__new-merchant-account.yaml
> +            visa_network_token_app_id: ca12b3d0-4e23-41a9-906f-e5cbb8e6a731
@victormferrara yeah that was probably a typo on my end. Happy to rename to plural.

2023-05-10 14:55 UTC, cbetta commented on reference/request-bodies/merchant_account_create.yaml
> +      Application ID provided by G+D for VISA after onboarding to use Network
```suggestion
      Application ID provided for VISA after onboarding to use Network
```
Let's keep G+D out of the docs.

2023-05-10 14:56 UTC, cbetta commented on reference/request-bodies/merchant_account_update.yaml
> +  visa_network_token_requestor_id:
Hmm, this is one for @brunodesde1987. I'm surprised the webhook API works as such. I'd expect them to be unset if explicitly set to null, not if committed.

2023-05-10 14:56 UTC, cbetta requested changes
Few changes requested

2023-05-10 17:51 UTC, victormferrara commented on reference/request-bodies/merchant_account_create.yaml
> +      Application ID provided by G+D for VISA after onboarding to use Network
Removed in https://github.com/gr4vy/gr4vy-openapi/pull/331/commits/b39dbf62856666ebf85774235cfb19ff5bd8e78b

2023-05-10 17:52 UTC, victormferrara commented on reference/request-bodies/merchant_account_create.yaml
> +      Requestor ID provided by VISA after onboarding to use Network Tokens.
I *think* you meant this: https://github.com/gr4vy/gr4vy-openapi/pull/331/commits/f8b1b10c4e3958011e5eb097b225d0e1d283d08d. Let me know if not.

2023-05-11 10:07 UTC, victormferrara commented on reference/paths/merchant-accounts__new-merchant-account.yaml
> +      fields or configuration doesn't meet uniqueness conditions.
I wasn't sure if violating the uniqueness conditions should be a 400 or a 409. I've seen both things in the code, but I'd say that we're mostly using the 409 when the main resource is the one that conflicts with the existing data, although maybe it was just coincidence.

2023-05-16 16:52 UTC, cbetta approved these changes

2023-05-16 17:59 UTC, cbetta commented on reference/paths/merchant-accounts__new-merchant-account.yaml
> +      fields or configuration doesn't meet uniqueness conditions.
Yes, I'd agree with this.

2023-05-17 12:19 UTC, federicojasson reviewed
**Note**: I forgot to hit the "Submit review" button 🤦‍♂️  so comments may be outdated 🙏

2023-05-17 12:52 UTC, victormferrara commented on reference/request-bodies/merchant_account_update.yaml
> +      Application ID provided by G+D for AMEX after onboarding to use Network
Thanks, done in https://github.com/gr4vy/gr4vy-openapi/pull/331/commits/d093b45bf5db5dee8b57af991d82b8907b0df975

2023-05-17 12:53 UTC, victormferrara commented on reference/request-bodies/merchant_account_update.yaml
> +  visa_network_token_requestor_id:
Agreed during sync to keep this behaviour.

2023-05-17 21:33 UTC, federicojasson approved these changes

2023-05-18 15:06 UTC, merged