feat: Add PCI Forwarding (TA-4592)
gr4vy/gr4vy-openapi pull request #353
Opened 2023-06-21 09:38 UTC by hasier

# Description

Jira: TA-4592

Add specs for PCI forwarding, definitions and configurations.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2023-06-21 09:39 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +          type: string
I was not sure if we wanted to add the whole explanation on how templates worked here or leave it for the guide instead, as I'm guessing it might be a bit extensive. Thoughts?

2023-06-21 10:26 UTC, szeying-lee commented on reference/resources/pci_forward_configs.yaml
> +  - Discovery
`x-tag` copied pasted from somewhere else? (Same for other resources)

2023-06-21 10:26 UTC, szeying-lee commented on reference/resources/pci_forward_config.yaml
> +    description: The ID of this payment service.
```suggestion
    description: The ID of this PCI forward configuration.
```

2023-06-21 10:26 UTC, szeying-lee commented on reference/resources/pci_forward_config.yaml
> +    maxLength: 200
Are these needed? 🤔

2023-06-21 10:26 UTC, szeying-lee commented on reference/paths/pci_forward__make-pci-forward.yaml
> +        type: string
Would it be worth to add an example request here?

2023-06-21 10:26 UTC, szeying-lee commented on reference/header-parameters/pci_forward_timeout.yaml
> +  default: 30
Maybe we can specify `min: 1` here too

2023-06-21 10:26 UTC, szeying-lee commented on reference/header-parameters/pci_forward_payment_methods.yaml
> +  template to forward.
Should we specify that this has a maximum of 100?

2023-06-21 10:30 UTC, hasier commented on reference/resources/pci_forward_configs.yaml
> +  - Discovery
I assumed it was necessary for the auto-import we do from Mintlify, but it's true not all files have it 🤔  I guess it's ok to drop it @cbetta?

2023-06-21 10:32 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +        type: string
Maybe, just not sure how much into detail we wanted to go, I was wondering [here](https://github.com/gr4vy/gr4vy-openapi/pull/353#discussion_r1236710075) whether we wanted to do so now or within the guide instead.

2023-06-21 10:32 UTC, szeying-lee commented on reference/resources/pci_forward_configs.yaml
> +  - Discovery
I wasn't sure if these need the `PCI Forward configurations` tag instead.. I think I'm a little lost though, not sure what the `Discovery` tag is meant to be used for

2023-06-21 10:32 UTC, hasier commented on reference/header-parameters/pci_forward_payment_methods.yaml
> +  template to forward.
Good one, done! https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/b8be4cc497e2bb9d0b1a816625c766ef94898452

2023-06-21 10:32 UTC, hasier commented on reference/header-parameters/pci_forward_timeout.yaml
> +  default: 30
Done! https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/8614950c123870f4d7bb87042221cf63871824ba

2023-06-21 10:33 UTC, hasier commented on reference/resources/pci_forward_config.yaml
> +    maxLength: 200
🤦  done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/a8841638c90ec3e57d050acac62ab072effbc7c4

2023-06-21 10:33 UTC, hasier commented on reference/resources/pci_forward_config.yaml
> +    description: The ID of this payment service.
☕ -🍝  https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/e9fd88990b2c0c118d3da9825ec189cb79075b84

2023-06-21 10:34 UTC, szeying-lee commented on reference/paths/pci_forward__make-pci-forward.yaml
> +          type: string
I'd say leave it for the guide 🤔 We did something similar with the documentation for `Reports`. Maybe we can link this section to the guide after.

2023-06-21 10:41 UTC, szeying-lee commented on reference/paths/pci_forward__make-pci-forward.yaml
> +        type: string
If we want, probably a simple example would suffice, just to illustrate how the API might be used. We can definitely go into more detail in the guide.

2023-06-21 11:31 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +        type: string
Maybe something like this? https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/19f44ab642f8a73b561e63251dd57fbf304d6be3

2023-06-21 11:38 UTC, cbetta requested changes
A few copy changes and some questions

2023-06-21 11:38 UTC, cbetta commented on reference/paths/pci_forward__make-pci-forward.yaml
> +summary: Make a PCI Forward request
```suggestion
summary: Forward PCI data
```

2023-06-21 11:38 UTC, cbetta commented on reference/paths/pci_forward__make-pci-forward.yaml
> +  gets sent to the given destination.
```suggestion
  Forward an API call to a PCI endpoint. The request body is evaluated
  and any template fields are replaced by the card data before the request is
  sent to the given destination.
```

2023-06-21 11:38 UTC, cbetta commented on reference/paths/pci_forward_configs__delete-pci-forward-config.yaml
> +description: Deletes a specific PCI Forward configuration.
```suggestion
summary: Remove a configured PCI Forward endpoint
description: |-
  Removes a previously configured PCI Forward endpoint, effectively disallowing
  data to be sent to this endpoint.
```

2023-06-21 11:38 UTC, cbetta commented on reference/paths/pci_forward_configs__list-pci-forward-configs.yaml
> +description: Lists the currently configured PCI Forward configurations.
```suggestion
summary: List configured PCI Forward endpoints
description: |-
  Lists the currently configured PCI Forward endpoints that can be used to forward
  PCI data to.
```

2023-06-21 11:38 UTC, cbetta commented on reference/paths/pci_forward_configs__new-pci-forward-config.yaml
> +description: Adds a new PCI Forward configuration.
```suggestion
summary: Enable new PCI Forward endpoint
operationId: new-pci-forward-config
description: |-
  Enables a new PCI Forward endpoint. This allows this endpoint
  to be used to forward PCI data to.
```

2023-06-21 11:38 UTC, cbetta commented on reference/paths/pci_forward_definitions__list-pci-forward-definitions.yaml
> +description: Returns a list of all available PCI Forward definitions.
```suggestion
operationId: list-pci-forward-definitions
summary: List PCI Forward definitions
description: |-
  Returns a list of definitions for all available endpoints that PCI data
  can be forwarded to.
```

2023-06-21 11:38 UTC, cbetta commented on reference/resources/pci_forward_config.yaml
> +    example: Amadeus
How is this set? Is it extracted from the definition?

2023-06-21 11:38 UTC, cbetta commented on reference/request-bodies/pci_forward_config_create_request.yaml
> +    example: amadeus
Can the same definition be set twice?

2023-06-21 11:38 UTC, cbetta commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
Did we consider that a config may require multiple hostnames?

2023-06-21 11:51 UTC, hasier commented on reference/resources/pci_forward_config.yaml
> +    example: Amadeus
Yes.

2023-06-21 11:51 UTC, hasier commented on reference/request-bodies/pci_forward_config_create_request.yaml
> +    example: amadeus
No, it will fail with a validation error.

2023-06-21 11:51 UTC, hasier commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
We did not 😅  I guess we assumed each definition would point to just 1 host, so for multiple hosts we'd have multiple definitions.

2023-06-21 11:56 UTC, hasier commented on reference/header-parameters/pci_forward_header.yaml
> +  as `HEADER_NAME`.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/header-parameters/pci_forward_header.yaml
> +  as `HEADER_NAME`.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/header-parameters/pci_forward_http_method.yaml
> +description: The HTTP method to use when forwarding the request.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/header-parameters/pci_forward_payment_methods.yaml
> +  template to forward.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/resources/pci_forward_definitions.yaml
> +description: A list of available PCI Forward definitions.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/header-parameters/pci_forward_url.yaml
> +description: The URL to PCI Forward the request to.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +summary: Make a PCI Forward request
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +  gets sent to the given destination.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/paths/pci_forward_configs__delete-pci-forward-config.yaml
> +description: Deletes a specific PCI Forward configuration.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 11:56 UTC, hasier commented on reference/paths/pci_forward_configs__new-pci-forward-config.yaml
> +description: Adds a new PCI Forward configuration.
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/473b06d3dc1e6b5518df4135d9fde0f6e0dd3799

2023-06-21 14:44 UTC, ipeluffo commented on reference/header-parameters/pci_forward_header.yaml
> +  `content-type: application/json`."
[minor]
```suggestion
description: |-
  A header that is forwarded to the `x-pci-forward-url`. The header will be
  forwarded without the `x-pci-forward` part. For example,
  `x-pci-forward-header-content-type: application/json` is forwarded as
  `content-type: application/json`.
```

2023-06-21 14:50 UTC, hasier commented on reference/header-parameters/pci_forward_url.yaml
> +  example: https://api.amadeus.com/booking
It felt this was more explicit, but it's a good point. Any preferences @cbetta?

2023-06-21 14:51 UTC, hasier commented on reference/header-parameters/pci_forward_header.yaml
> +  `content-type: application/json`."
Done https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/13e4860e3e9b9cad32b00256aa5fcec9c6fe6d54

2023-06-21 14:53 UTC, ipeluffo commented on reference/header-parameters/pci_forward_header.yaml
> +  `content-type: application/json`."
```suggestion
  A header that is forwarded to the `x-pci-forward-url`. The header will be
  forwarded without the `x-pci-forward-header` part. For example,
  `x-pci-forward-header-content-type: application/json` is forwarded as
  `content-type: application/json`.
```
[minor]

2023-06-21 14:58 UTC, ipeluffo commented on reference/paths/pci_forward__make-pci-forward.yaml
> +    description: Returns the payload received from the forwarded request.
Should we mention that we also return this for client errors like timeouts?

2023-06-21 15:02 UTC, ipeluffo commented on reference/resources/pci_forward_config.yaml
> +    description: "`pci-forward-config`."
```suggestion
    description: "`pci-forward-config`"
```

2023-06-21 15:03 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +    description: Returns the payload received from the forwarded request.
Something like this? https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/e0469ecb2635ac3f95dddcdd7682ca71de0f7d9b

2023-06-21 15:15 UTC, ipeluffo reviewed
LGTM, maybe a final approval from @cbetta

2023-06-21 15:38 UTC, szeying-lee submitted a review, later dismissed

2023-06-26 13:10 UTC, cbetta commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
I think this may be limiting down the line seeing as I think some services will operate on subdomains. E.g. `[brand].domain.com`. We can fix this when we get a customer looking to go live.

2023-06-26 13:11 UTC, cbetta commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
Also do we store the full domain or just the hostname? E.g. `domain.com` vs `https://domain.com`?

2023-06-26 13:15 UTC, cbetta commented on reference/header-parameters/pci_forward_url.yaml
> +  example: https://api.amadeus.com/booking
This is fine

2023-06-26 13:20 UTC, cbetta commented on reference/paths/pci_forward__make-pci-forward.yaml
> +          value: '{"number":"{{CARD_NUMBER_1}}","expiry":"{{CARD_EXPIRATION_DATE_1}}"}'
Yaml actually supports multi line strings. This would make for a much nicer example.

```suggestion
          value: "{
            "number":"{{CARD_NUMBER_1}}",
            "expiry":"{{CARD_EXPIRATION_DATE_1}}"  
          }"
```

2023-06-26 13:50 UTC, cbetta commented on reference/request-bodies/pci_forward_config_create_request.yaml
> +    example: amadeus
Can we capture this in the errors somehow as well as the description?

2023-06-26 13:55 UTC, hasier commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
> @hasier does the PCI forwarding allow forwarding to subdomains? E.g. it allows `domain.com` can I push to `foo.domain.com`?

> I think this may be limiting down the line seeing as I think some services will operate on subdomains. E.g. [brand].domain.com. We can fix this when we get a customer looking to go live.

We do allow using subdomains. However, currently the host in the URL needs to match the full host in the definition. So a definition like `https://domain.com` won't accept `https://sub.domain.com`. A definition may set a host as `https://sub.domain.com` and it will allow pushing to that specific subdomain.

We can look into allowing multiple hosts per definition as a list if you feel it's going to be a blocker. Allowing subdomains automatically might be trickier, so probably we can just add specific subdomain hosts to the list of hosts per definition if we implemented the list option.

> Also do we store the full domain or just the hostname? E.g. `domain.com` vs `https://domain.com`?

We currently store the full domain as `https://domain.com` (although it's always forced to be `https` anyway).

2023-06-26 13:55 UTC, hasier commented on reference/paths/pci_forward__make-pci-forward.yaml
> +          value: '{"number":"{{CARD_NUMBER_1}}","expiry":"{{CARD_EXPIRATION_DATE_1}}"}'
Somehow I did not get it to work the first time and `prettier` was messing with it. Fixed now https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/e22b62446062ec59c7466662d820db64ae95ee41

2023-06-26 13:58 UTC, hasier commented on reference/resources/pci_forward_configs.yaml
> +  - Discovery
Nice, done! https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/ec1d05e9705b96be40740616f4fa7fba5802ac64

2023-06-26 14:16 UTC, hasier commented on reference/request-bodies/pci_forward_config_create_request.yaml
> +    example: amadeus
Done, wdyt? https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/9d66a32d8d664a15a2761c16d6a6ad0a452a43e5

2023-06-26 15:52 UTC, cbetta commented on reference/request-bodies/pci_forward_config_create_request.yaml
> +    example: amadeus
I think this needs to return a 409, should it not? Also please check the API spec for other examples on how we documented 409s.

2023-06-26 15:56 UTC, cbetta commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
I don't think auto-allowing subdomains is a good idea (it's a security issue actually), so let's not do that. I really think we should allow fir multiple hostnames, and I also think it's likely to be a backwards incompatible change, so it might be good to fix now.

I am in 2 minds on wether we should store the full domain or just the hostname (e.g. drop https). I can't tell what other scheme we would ever want to allow, except for maybe HTTP on localhost for devs?

2023-06-26 16:07 UTC, hasier commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
Will tackle the multiple hosts bit right away [TA-4806](https://gr4vy.atlassian.net/browse/TA-4806)

About the full domain, we didn't do the `https` bit on purpose, it was just more straightforward like this with the validation tooling we were using. In any case, I can think maybe in the future we want to look into (s)FTP(s) stuff? Not sure it's that big a thing anyway, considering the clients don't need to type that host anywhere and it's only us that handle it internally, so maybe we are good with it for now?

2023-06-27 10:18 UTC, hasier commented on reference/request-bodies/pci_forward_config_create_request.yaml
> +    example: amadeus
Done! https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/b15594dbfbb7c30f051886f5aa8b6a2c6430dac5

2023-06-29 08:34 UTC, hasier commented on reference/resources/pci_forward_definition.yaml
> +    example: https://api.amadeus.com
TA-4806 merged in Core API and docs updated here https://github.com/gr4vy/gr4vy-openapi/pull/353/commits/b85a3ab1401c03ba9aca809ec021a554d98bcb26

2023-06-29 11:24 UTC, cbetta approved these changes

2023-07-04 10:36 UTC, merged