feat(checkout-sessions): add cart items and metadata to checkout session
gr4vy/gr4vy-openapi pull request #367
Opened 2023-07-10 09:23 UTC by douglaseggleton

# Description

Adds `metadata` and `cart_items` to checkout sessions.

![2023-07-10 10 20 50](https://github.com/gr4vy/gr4vy-openapi/assets/1008377/9b1821f2-1772-4ef3-98fc-f6678f1db00e)

https://gr4vy.atlassian.net/browse/TA-4879

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2023-07-10 15:11 UTC, cbetta commented
@douglaseggleton perfect, it's exactly what I had in mind.

It might be good to talk to @bloowitt as well. He's working on a change to the Cart Items at the moment in CoreAPI.

2023-08-04 10:46 UTC, cbetta commented on reference/resources/checkout_session.yaml
> +    maxItems: 249
I think there's no limit anymore now. Right @bloowitt ?

```suggestion
```

2023-08-04 10:48 UTC, cbetta commented on reference/request-bodies/checkout_session_update_request.yaml
> +    maxItems: 249
```suggestion
```

2023-08-04 10:49 UTC, cbetta requested changes
I think we can drop the 249 limit now on cart items since this week.

2023-08-07 09:36 UTC, cbetta commented
@douglaseggleton alex is out this week. I checked CoreAPI and we indeed dropped the 249 limit

2023-08-07 15:31 UTC, cbetta commented on reference/request-bodies/checkout_session_create_request.yaml
> +    maxItems: 249
This can go

2023-08-07 18:28 UTC, douglaseggleton commented on reference/request-bodies/checkout_session_create_request.yaml
> +    maxItems: 249
```suggestion
```

2023-08-08 10:47 UTC, cbetta approved these changes

2023-08-08 12:33 UTC, merged