feat(account-updater): Document last_replaced_at and has_replacement fields [TA-4951]
gr4vy/gr4vy-openapi pull request #377
Opened 2023-07-26 19:58 UTC by federicojasson

# Description

Jira: TA-4951

This PR documents the new payment method fields related with the Account Updater feature:
- `last_replaced_at`
- `has_replacement`

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2023-07-26 21:25 UTC, cbetta commented on reference/resources/payment_method--tokenized.yaml
> +      This value is always `null` for non-card payment methods.
@federicojasson I think it would make sense to explain what would cause a replacement here. E.g. an account updater.

Also, why is this not called `last_updated_at`?

2023-07-26 21:26 UTC, cbetta commented on reference/resources/payment_method--tokenized.yaml
> +      This value is always `false` for non-card payment methods.
```suggestion
      Whether this card has a pending replacement that hasn't been applied yet.
      This value is always `false` for non-card payment methods.
```

If it's always a card then let's call it a card.

Again, I think this needs a bit more explanation as to what a "replacement" is. E.g. a new set of card details.

2023-07-26 21:26 UTC, cbetta requested changes
Left some comments. Also not sure about the `replace` terminology over `update`.

2023-07-27 09:23 UTC, cbetta commented
@federicojasson also, when/where are we documenting the endpoints to request an update?

2023-07-27 09:34 UTC, federicojasson commented on reference/resources/payment_method--tokenized.yaml
> +      This value is always `null` for non-card payment methods.
Sure, I can add some more details. Eventually we may also want a section in the [docs](https://github.com/gr4vy/gr4vy-docs-mintlify) that explains in detail what Account Updater is and how it works.

2023-07-27 09:37 UTC, federicojasson commented
@cbetta

> Also not sure about the `replace` terminology over `update`.

I'd say that "update" is overloaded in this context, since we have an `updated_at` field, which refers to any change, not just to card details. WDYT?

> when/where are we documenting the endpoints to request an update?

This will be documented in TA-4823 (PR coming later today).

2023-07-27 09:45 UTC, cbetta commented
> @cbetta
> 
> > Also not sure about the `replace` terminology over `update`.
> 
> I'd say that "update" is overloaded in this context, since we have an `updated_at` field, which refers to any change, not just to card details. WDYT?
> 
> > when/where are we documenting the endpoints to request an update?
> 
> This will be documented in TA-4823 (PR coming later today).
> 

I agree. Yet this feature will be sold as an Account Updated. Not a Card Replacer. I wonder if it makes sense to stay closer to the language a merchant would expect.

2023-07-27 13:01 UTC, jadk89 commented
I think it's ok to leave it as "last_replaced_at" and "has_replacement", reason for these two fields is we might have an updated card while the old card is not yet expired, we will try with the old card until it gets declined or expires. We then have a replacement for the card available. For any other type of update we indeed have the `updated_at` field.

2023-07-27 16:59 UTC, federicojasson commented on reference/resources/payment_method--tokenized.yaml
> +      This value is always `null` for non-card payment methods.
Done: [Extend descriptions of new fields](https://github.com/gr4vy/gr4vy-openapi/pull/377/commits/eaf2761ecc766374fd277474ed635b71e1c94c36)

2023-07-27 17:00 UTC, federicojasson commented on reference/resources/payment_method--tokenized.yaml
> +      This value is always `false` for non-card payment methods.
Done: [Extend descriptions of new fields](https://github.com/gr4vy/gr4vy-openapi/pull/377/commits/eaf2761ecc766374fd277474ed635b71e1c94c36)

2023-07-27 17:27 UTC, jadk89 approved these changes

2023-07-31 09:26 UTC, cbetta approved these changes

2023-07-31 14:38 UTC, merged