3d secure design
gr4vy/gr4vy-openapi pull request #39
Opened 2021-06-07 11:00 UTC by steve-gr4vy

# Description

Adding support for 3D Secure flows

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2021-06-07 12:53 UTC, cbetta commented on reference/openapi.yaml
> -
Tnx for removing this.

2021-06-07 12:57 UTC, cbetta commented on reference/paths/transactions__post-approve-transaction.yaml
> +            threeds_transaction_status: "N"
Is this `N` just an example value?

2021-06-07 13:00 UTC, steve-gr4vy commented on reference/paths/transactions__post-approve-transaction.yaml
> +            threeds_transaction_status: "N"
Yes, whatever is passed back from the issuer in the cRes should be passed in this field, however cardinal's examples show an N or Y in this field, hence the example value of 'N'

2021-06-07 13:10 UTC, cbetta requested changes

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/threeds_data_request.yaml
> +      The version of 3D Secure used.
```suggestion
      The version of 3-D Secure used. 
```

2021-06-07 13:10 UTC, cbetta commented on reference/openapi.yaml
> +    ThreeDSDataRequest:
Let's stick to 3-D Secure and `3d_secure`

2021-06-07 13:10 UTC, cbetta commented on reference/openapi.yaml
> +    ThreeDSDataRequest:
```suggestion
    3DSecureData:
```

2021-06-07 13:10 UTC, cbetta commented on reference/openapi.yaml
> +    ThreeDSDataRequest:
Actually, this does not need to be its own schema. We should just define this straight in the card request schema.

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/transaction_approve_request.yaml
> +  threeds_transaction_status:
```suggestion
  3d_secure_transaction_status:
```

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/transaction_approve_request.yaml
> +description: A request to capture a transaction.
```suggestion
description: A request to approve the 3D secure step of a card transaction.
```

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/transaction_approve_request.yaml
> +title: Approve a transaction
```suggestion
title: Complete a 3D Secure transaction
```

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/transaction_create_request.yaml
> +  threeds_data:
```suggestion
  3d_secure_data:
```

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/transaction_create_request.yaml
> +    x-model-name: TransactionThreeDSecureDataRequest
Not needed

2021-06-07 13:10 UTC, cbetta commented on reference/request-bodies/transaction_create_request.yaml
> +    $ref: "../openapi.yaml#/components/schemas/ThreeDSDataRequest"
I'd just embed this data in this schema.

2021-06-07 13:10 UTC, cbetta commented on reference/resources/transaction.yaml
> +    nullable: true
Hmm. Not sure what we want to capture here. That a transaction had 3D Secure performed? What if it failed? What if it hasn't completed yet?

2021-06-07 16:20 UTC, cbetta commented on reference/paths/transactions__post-approve-transaction.yaml
> +            threeds_transaction_status: "N"
Cool. My only change would be to update this to:

```suggestion
            3d_secure_transaction_status: "N"
```

2021-06-10 08:44 UTC, cbetta commented on reference/request-bodies/threeds_data_request.yaml
> +  Data from an external `3-D` Secure MPI that can be used to successfully create the transaction.
Why `3-D`? Spell checker getting in the way?

2021-06-10 08:54 UTC, steve-gr4vy commented on reference/request-bodies/threeds_data_request.yaml
> +  Data from an external `3-D` Secure MPI that can be used to successfully create the transaction.
Yes, spell checker didn't like 3-D, hence the backticks

2021-06-11 09:38 UTC, cbetta commented on reference/request-bodies/threeds_data_request.yaml
> +  Data from an external `3-D` Secure MPI that can be used to successfully create the transaction.
Ok. A nicer way to resolve this is to add the term to the `.spelling` file.

2021-09-23 14:16 UTC, douglaseggleton commented
Closing this PR in favour of https://github.com/gr4vy/gr4vy-openapi/pull/65
(A lot has changed so thought it was better to just create a new PR and copy the stuff thats needed across)

2021-09-23 14:16 UTC, closed without merging