feat: Add webhook endpoint/url to Payment Service resource
gr4vy/gr4vy-openapi pull request #94
Opened 2022-01-14 11:45 UTC by ipeluffo

# Description
https://gr4vy.atlassian.net/browse/TA-638

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-01-14 11:45 UTC, ipeluffo commented on reference/resources/payment_service.yaml
> +  webhook_url:
Is this ok or it should be `webhook_endpoint` or something else? Thanks

2022-01-17 09:37 UTC, gryevns commented on reference/resources/payment_service.yaml
> +  webhook_url:
I went with `webhook_url` via https://github.com/gr4vy/core-api/pull/527 because we also have `merchant_url`.

2022-01-17 09:37 UTC, gryevns approved these changes

2022-01-17 09:46 UTC, cbetta commented on reference/resources/payment_service.yaml
> +      the payment service.
```suggestion
      The URL that needs to be configured with this payment service as the receiving
      endpoint for webhooks from the service to Gr4vy. Currently, Gr4vy does not yet 
      automatically register webhooks where possible.
```

2022-01-17 09:46 UTC, cbetta requested changes
Left a more imperative description for this URL.

2022-01-17 17:11 UTC, gryevns approved these changes

2022-01-17 17:35 UTC, cbetta approved these changes

2022-01-17 17:36 UTC, merged