feat: TA-92 - Add new refund/void transaction endpoints
gr4vy/gr4vy-openapi pull request #98
Opened 2022-01-25 19:37 UTC by federicojasson

# Description

This PR introduces the new refund/void transaction endpoints, while puts a deprecation warning on the old one.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own changes
- [X] I have run `yarn test` to make sure my changes pass all linters
- [X] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2022-01-25 19:38 UTC, federicojasson commented
This PR should probably be merged only after the feature is implemented.

2022-01-26 08:52 UTC, bloowitt requested changes
Left a comment on endpoint behaviour

2022-01-26 08:52 UTC, bloowitt commented on reference/paths/transactions__refund-transaction.yaml
> +  If the transaction was not yet captured, the behaviour depends on the
According to TA-91:
```
The existing refund endpoint in the connector will need to be split into separate void and refund endpoints. Each will return a failed response when the action is not applicable:

    void will fail if the transaction is processing or already captured

    refund will fail if the transaction has not yet been captured
```
  So it should not reach the PSP if the status is not appropriate. Something like "the transaction needs to have been captured for this endpoint to work`?

2022-01-26 12:32 UTC, cbetta commented on reference/paths/transactions__refund-transaction.yaml
> +  If the transaction was not yet captured, the behaviour depends on the
Yes. 100% this. This new endpoint will only process the refund if the transaction status is `capture_succeeded` (check status in core API to confirm spelling)

2022-01-26 12:33 UTC, cbetta commented on reference/paths/transactions__refund-transaction.yaml
> +  [Void transaction](#operation/void-transaction) endpoint instead.
```suggestion
  If the transaction was not yet successfully captured the refund will not be processed.
```

2022-01-26 12:34 UTC, cbetta commented on reference/paths/transactions__refund-transaction.yaml
> +          value: {}
Do we want to support an empty request body?

2022-01-26 12:36 UTC, cbetta commented on reference/paths/transactions__void-transaction.yaml
> +  [Refund transaction](#operation/refund-transaction) endpoint instead.
```suggestion
  If the transaction was not yet successfully authorized, or already captured the void
  will not be processed. Captured transactions can be [refunded](#operation/refund-transaction)
  instead.
```

2022-01-26 12:36 UTC, cbetta commented on reference/request-bodies/transaction_refund_request.yaml
> +      The amount requested for refund.
```suggestion
      The amount requested to refund.
```

2022-01-26 12:37 UTC, cbetta commented on reference/request-bodies/transaction_refund_request.yaml
> +      in the associated transaction.
```suggestion
      If omitted, a full refund will be requested.
      Otherwise, the amount must be lower than or equal to the remaining balance
      in the associated transaction. Negative refunds are not supported.
```

2022-01-26 12:37 UTC, cbetta commented on reference/resources/refund.yaml
> +    enum:
Are these states based on @danielknell's initial list?

2022-01-26 12:38 UTC, cbetta commented on reference/resources/refund.yaml
> +    description: The transaction identifier in the underlying PSP.
```suggestion
    description: The refund identifier in the underlying PSP.
```

2022-01-26 12:39 UTC, cbetta commented on reference/resources/refund.yaml
> +
Every resource at Gr4vy requires an `id` and `type`. Type here should be `refund`.

2022-01-26 12:40 UTC, cbetta commented on reference/resources/refund.yaml
> +    maxLength: 300
Do we return the `xid` anywhere else in our API? I don't think we do. Please leave it out, as I think the term `xid` is purely internal atm.

2022-01-26 12:40 UTC, cbetta commented on reference/paths/transactions__void-transaction.yaml
> +          value: {}
I think we can leave this whole request body out as it's empty. It's basically a `POST` without a body.

2022-01-26 12:41 UTC, cbetta requested changes
Requested a few changes to the copy, as well as some structural ones.

2022-01-26 12:46 UTC, federicojasson commented on reference/resources/refund.yaml
> +    enum:
Based on https://gr4vy.atlassian.net/wiki/spaces/GB/pages/153125577/Refund+model

2022-01-26 13:15 UTC, federicojasson commented on reference/paths/transactions__refund-transaction.yaml
> +          value: {}
Well, it's the default state of the object when all optional fields (in this case, just `amount`) are left out. Also, I'm not sure how to display the example more clearly than with an empty object, which contrasts with the partial refund example.

2022-01-26 13:27 UTC, danielknell commented on reference/resources/refund.yaml
> +    maxLength: 300
the only place we expose xid currently is the `tokens` endpoint which renames it to `id`

2022-01-26 17:02 UTC, bloowitt submitted a review, later dismissed
LGTM now, I'll leave it in @cbetta's hands

2022-01-28 09:54 UTC, epigos submitted a review, later dismissed
LGTM

2022-02-01 10:15 UTC, cbetta commented on reference/paths/transactions__refund-transaction.yaml
> +          value: {}
Yeah fine as is.

2022-02-01 10:21 UTC, cbetta approved these changes
LGTM!

2022-02-03 17:02 UTC, bloowitt approved these changes

2022-02-07 19:11 UTC, merged